[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "1.0.5" }

[dependencies]
pgn-reader = "0.26.0"
risc0-zkvm = "1.0.5"
shakmaty = "0.27.1"

[package.metadata.risc0]
methods = ["guest"]
